<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version Condition="'$(Version)' == ''">0.0.0-local</Version>

        <!-- FileVersion & AssemblyVersion — dihitung dari $(Version) -->
        <FileVersion>$(Version.Split('-')[0]).0</FileVersion>
        <AssemblyVersion>$(Version.Split('-')[0]).0</AssemblyVersion>

        <!-- Metadata umum -->
        <Authors>Abdul Azis</Authors>
        <Company>Eventra</Company>
        <Copyright>Copyright © 2026 Abdul Azis</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/azizp2/Eventra</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://azizp2.github.io/EventraDocs/</PackageProjectUrl>

        <!-- Build settings -->
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile Condition="'$(IsPackable)' != 'false'">true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>