<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Cacah.Eventra</PackageId>
    <Version>1.0.0</Version>
    <Authors>Abdul Azis</Authors>
    <Description>Domain Events framework di atas MediatR.</Description>
    <PackageProjectUrl>https://github.com/azizp2/Eventra</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
