<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Eventra.Abstractions</PackageId>
    <Description>Core abstractions for Eventra — domain events for .NET.</Description>
    <PackageTags>dotnet;csharp;domain-events;ddd;clean-architecture;mediatr-alternative;zero-dependency</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>